Azure/kubernetes-kms

- .gitignore
- Dockerfile
- README.md
- server.go
- test/client.go
- v1beta1/service.pb.go
- v1beta1/service.proto
Renaming due to this https://github.com/kubernetes/kubernetes/pull/60268
> Rename KMSService to KeyManagementService

- Gopkg.lock
- Makefile
- developers.md
- kubernetes/kube-azurekmspod.yaml
> Update kms image

- manual-install.md
Fixes https://github.com/kubernetes/kubernetes/issues/65953
> Update manual-install doc to create storage account

- Makefile
- oauth.go
- server.go
- server_test.go
> Fix support for sovereign cloud

- Gopkg.lock
- Makefile
- oauth.go
- server.go
Fixes #38 
- Update Azure Config struct to match the latest from K8s azure cloud provider: https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/azure/azure.go#L76-L141
- Use json parser to update `providerKeyVersion` in azure.json
> Use JSON parser for updating config

- README.md
Removing AKS section as AKS doesn't use KMS today.
> docs: Removing AKS section as AKS doesn't use KMS today.

- CONTRIBUTING.md
- README.md
Some changes to the README.md to improve consistency:
* Refer to the project consistently as "KMS Plugin for Key Vault"
* Add CircleCI badge
* Change **How to use** to the more standard **Getting Started**
* Move most URL targets to the bottom for DRY and readability
* Fix lots of markdown linting complaints
* Move **Contributing** to a standalone document as recommended by GitHub [community standards](https://github.com/Azure/kubernetes-kms/community)
* Rewrite intro and any language that was confusing (to me)
None, but see also Azure/kubernetes-keyvault-flexvol#105
[This view](https://github.com/Azure/kubernetes-kms/blob/fe9b515b0ddbd6c83285f08bd3f2d25049723271/README.md) may be easier to read than the diff.
> docs: clean up README.md

- README.md
- Adds azure pipeline build badge to readme
> docs: add build badges

- .gitignore
- .pipelines/unit-tests-template.yml
- Makefile
- Updates pipeline to run unit tests only for the kms plugin
- Updates go version to `1.15`
> test: update pipeline for unit tests

- Makefile
- manual-install.md
- server.go
> release: bump version to v0.0.10

- .gitignore
- .pipelines/e2e-kind-template.yml
- .pipelines/pr.yml
- .pipelines/unit-tests-template.yml
- Makefile
- docs/testing.md
- pkg/config/azure_config.go
- pkg/plugin/keyvault.go
- scripts/ci-e2e-kind.sh
- tests/e2e/azure.json
- tests/e2e/encryption-config.yaml
- tests/e2e/helpers.bash
- tests/e2e/kms.yaml
- tests/e2e/test.bats
- Adds e2e tests with kind cluster
> test: add e2e tests with kind cluster

- .pipelines/unit-tests-template.yml
- Dockerfile
- tests/e2e/kms.yaml
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
Fixes #83 
> change base image to distroless/static

- pkg/auth/auth.go
- pkg/auth/auth_test.go
- Fixes the resource URL for managed identity scenarios
fixes #98 
> fix: use keyvault endpoint as resource for token request with msi

- .pipelines/pr.yml
- .pipelines/templates/e2e-upgrade-template.yml
- .pipelines/templates/soak-test-template.yml
- tests/e2e/test.bats
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
> test: soak tests

- docs/manual-install.md
- docs/rotation.md
> docs: add securityContext to pod manifest

- .pipelines/pr.yml
- .pipelines/templates/e2e-upgrade-template.yml
- .pipelines/templates/soak-test-template.yml
- tests/e2e/test.bats
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
This PR enables metrics endpoint test and fixes flake for nightly soak test.
fixes: #110 #106 
> fix: fixes flake and enables metrics test

- cmd/server/main.go
- pkg/auth/auth.go
- pkg/plugin/keyvault.go
- pkg/plugin/keyvault_test.go
- pkg/plugin/server.go
- tests/e2e/kms.yaml
- Adds support for managed HSM (`--managed-hsm=true`
- Refactors tests to separate out error and non-error scenarios (xref: https://github.com/golang/go/wiki/TestComments#table-driven-tests-vs-multiple-test-functions)
fixes #125 
> feat: add support for managed HSM

- .pipelines/nightly.yml
- .pipelines/pr.yml
- .pipelines/templates/e2e-kind-template.yml
- .pipelines/templates/e2e-upgrade-template.yml
- .pipelines/templates/manifest-template.yml
- .pipelines/templates/scan-images-template.yml
- .pipelines/templates/unit-tests-template.yml
- docs/testing.md
- tests/e2e/azure.json
> ci: switch to upstream ado org for e2e

- .pipelines/pr.yml
- README.md
- Updates build badge url
- Adds release version badge
- Adds skip paths for CI
> docs: update build badge url and add release badge

- .github/workflows/create-release.yml
- .goreleaser.yml
- Use goreleaser for generating changelog when a new tag is published
Testing in my fork: https://github.com/aramase/kubernetes-kms/releases/tag/v0.3.0
> ci: add goreleaser workflow for release

- .pipelines/templates/e2e-kind-template.yml
- Enable kind cluster matrix for e2e
> test: enable e2e with kind cluster matrix

- Makefile
- docs/manual-install.md
- docs/rotation.md
> release: bump version to v0.4.0

- README.md
Signed-off-by: Rita Zhang <rita.z.zhang@gmail.com>
Fixes #99 
> docs: update AKS feature

- README.md
Adding a link to the public roadmap to the README
None
> docs: add roadmap link to readme

- .golangci.yml
- cmd/server/main.go
- pkg/auth/auth.go
- pkg/config/azure_config.go
- pkg/metrics/exporter.go
- pkg/metrics/prometheus_exporter.go
- pkg/metrics/stats_reporter.go
- pkg/plugin/healthz.go
- pkg/plugin/healthz_test.go
- pkg/plugin/keyvault.go
- pkg/plugin/server.go
- pkg/plugin/server_test.go
- pkg/utils/grpc.go
- pkg/utils/sanitize.go
- pkg/version/version.go
- pkg/version/version_test.go
- tests/client/client_test.go
add/update list of linters and fixes
> chore: update linters

- .pipelines/nightly.yml
- .pipelines/pr.yml
- Makefile
- switch to using mariner pool for PRs and nightly jobs
> ci: switch to using mariner pool

- .github/workflows/codeql.yaml
> feat: adds CodeQL

- .github/semantic.yml
- make semantic check title only
> ci: make semantic check title only

- docs/manual-install.md
- docs/rotation.md
xref: https://github.com/kubernetes/community/blob/master/sig-architecture/naming/recommendations/001-master-control-plane.md
> docs: use control plane instead of master

- tests/client/client_test.go
> feat: Integration tests for KMS v2

- Dockerfile
> chore: switch to using mcr image
