Azure/kubernetes-kms

- Gopkg.lock
- server.go
> Fix racing condition using leasing on blob

- .circleci/config.yml
- Makefile
- developers.md
- oauth.go
- server.go
- Store `providerKeyVersion` in azure.json
- Store keyversion after a new key is created
- Get latest keyversion if key already exists and if`providerKeyVersion` is `""` in azure.json
- limit leastblob to `60` seconds instead of unlimited `-1`
- make `configFilePath` configurable
- Update developer doc
- Update KMS provider version to `v0.0.3`
> Persist keyversion in KMS provider config, limit leaseblob to 60s

- Makefile
- oauth.go
- server.go
Fixes https://github.com/Azure/aks-engine/issues/49
- When an encrypt request or a decrypt request occurs during a config (azure.json) update, config can be nil as the content is inflight. Handle nil config during a config update.
- Update the local `providerKeyVersion` property once we get a keyversion from keyvault so that we only update the config when `providerKeyVersion` is empty
> Fix issue caused by updating azure.json

- CODE_OF_CONDUCT.md
Adds the Microsoft Open Source Code of Conduct as a standalone document in the project root, as expected by GitHub [community standards](https://github.com/Azure/kubernetes-kms/community).
None, but see also Azure/aks-engine#510
> docs: add standalone Code of Conduct doc where GH can see it

- .gitignore
- .pipelines/pr.yml
- .pipelines/scan-images.yml
- .pipelines/unit-tests-template.yml
- Dockerfile
- Makefile
- Switches to using debian base image. 
- `distroless` image is currently not used because of dep on azure.json
- Enables image vuln scanning as part of CI
- Refactors Makefile
fixes #58 
fixes #68
> feat: switch to debian base image

- Dockerfile
> chore: update debian-base image to buster-v1.3.0

- cmd/server/main.go
- pkg/plugin/healthz.go
- pkg/plugin/healthz_test.go
- tests/e2e/kms.yaml
- tests/e2e/test.bats
- Adds `healthz` check for kms plugin
- `kube-apiserver` performs a health check on the kms plugin every 20s
- This checks encrypt and decrypt 
fixes https://github.com/Azure/kubernetes-kms/issues/62
> feat: add healthz check for kms plugin

- .pipelines/e2e-kind-template.yml
- .pipelines/unit-tests-template.yml
- Dockerfile
- go.mod
- go.sum
- pkg/auth/auth.go
- pkg/config/azure_config.go
- pkg/plugin/healthz_test.go
- tools/go.mod
- tools/go.sum
- Update to go 1.16
- Migrate from deprecated `io/ioutil` package to using `os` or `io` (https://golang.org/doc/go1.16#ioutil)
> chore: update to go 1.16

- .pipelines/nightly.yml
- Dockerfile
- Adds nightly test pipeline
- Fixes CVE-2021-24032
```bash
e2e/kubernetes-kms:test (debian 10.7)
=====================================
Total: 1 (MEDIUM: 1, HIGH: 0, CRITICAL: 0)
+----------+------------------+----------+-------------------+----------------------+--------------------------------+------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |    FIXED VERSION     |             TITLE              |                URL                 |
+----------+------------------+----------+-------------------+----------------------+--------------------------------+------------------------------------+
| libzstd1 | CVE-2021-24032   | MEDIUM   | 1.3.8+dfsg-3      | …
```
> ci: add nightly pipeline and fix CVE-2021-24032

- README.md
- docs/manual-install.md
- docs/rotation.md
> docs: add rotation guide

- cmd/server/main.go
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
Deprecates `configFilePath` and introduces hyphen separated `config-file-path`
fixes https://github.com/Azure/kubernetes-kms/issues/101
> fix: deprecates configFilePath

- cmd/server/main.go
- docs/manual-install.md
- pkg/plugin/keyvault.go
- pkg/plugin/keyvault_test.go
- pkg/utils/sanitize.go
- pkg/utils/sanitize_test.go
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
Removes double quotes from keyvault name.
fixes https://github.com/Azure/kubernetes-kms/issues/85
> fix: handles key vault name with double quotes.

- cmd/server/main.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/consts/consts.go
- pkg/plugin/keyvault.go
- pkg/plugin/keyvault_test.go
- pkg/plugin/server.go
This PR is to support KMS Plugin in AKS. The KMS Plugin is a sidecar of kube-apiserver pod. Due to security reasons, the KMS plugin may not access Key Vault. This PR will add a proxy mode so that the requests can be forwarded to the proxy, then the proxy can forward the requests to Key Vault.
N/A
Needs to release a new image
> Support proxy mode in case kms-plugin can not access key vault

- cmd/server/main.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/config/azure_config.go
- pkg/metrics/exporter.go
- pkg/metrics/prometheus_exporter.go
- pkg/plugin/healthz.go
- pkg/plugin/server.go
- pkg/plugin/server_test.go
- pkg/utils/grpc.go
- Updates all the logs to use structured logging with klog
- Replaced `Fatalf` with `ErrorS` followed by `os.Exit(1)` as recommended in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions-to-structured-equivalent
- Fix imports structure across all the packages. The format used in this project is
```bash
import (
std packages
internal packages
external packages
)
```
> chore: use structured logging and update imports order

- README.md
- docs/manual-install.md
AKS engine is being deprecated, this is a docs change to remove the reference to it from the README.
fixes #136
> remove aks engine instructions from README

- go.mod
- go.sum
```bash
┌──────────────────┬────────────────┬──────────┬──────────────────────────────────────┬───────────────┬──────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │          Installed Version           │ Fixed Version │                            Title                             │
├──────────────────┼────────────────┼──────────┼──────────────────────────────────────┼───────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-41717 │ MEDIUM   │ v0.3.1-0.20221206200815-1e63c2f08a10 │ 0.4.0         │ An attacker can cause excessive memory growth in a Go server │
│                  │                │ …
```
> security: fix CVE-2022-41717

- .pipelines/templates/e2e-kind-template.yml
- enable tests with kubernetes v1.26 
- remove kubernetes version 1.22 (EOL)
- update kubernetes versions for supported releases
> ci: enable tests with kubernetes v1.26 

- Makefile
We have updated mariner pools to install this package (gettext) during preprovison. Not longer need to manual install this
> chore: remove manual gettext/envsubst install

- Makefile
The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
xref: https://github.com/kubernetes/k8s.io/issues/2396
> chore: use `dl.k8s.io` instead of hardcoded url

- go.mod
- go.sum
- bump golang.org/x/net to v0.23.0+ to fix CVE-2023-45288
> security: bump golang.org/x/net to v0.23.0+ to fix CVE-2023-45288

- .github/workflows/scorecards.yml
Updating `ossf/scorecard-action` to latest (v2.3.1) to resolves [failures](https://github.com/Azure/kubernetes-kms/actions/runs/8742259890/job/23990093097).
xref: https://github.com/ossf/scorecard-action/issues/997
> ci: bump ossf/scorecard-action to v2.3.1

- tests/e2e/azure.json
- use msi to authenticate with keyvault
As we're using kind clusters for CI, we can leverage the ado-agent identity to authenticate with keyvault. With this change, we can get rid of the service principal.
> ci: use msi to authenticate with keyvault

- .pipelines/templates/e2e-kind-template.yml
- .pipelines/templates/e2e-upgrade-template.yml
- .pipelines/templates/manifest-template.yml
- .pipelines/templates/unit-tests-template.yml
- PR to cleanup references to `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` in the pipelines.
- Also using this to validate pipelines work as expected after removing the client id and secret variables from library.
> ci: use msi to authenticate with keyvault (cleanup)

- .github/workflows/create-release.yml
- .goreleaser.yml
- .pipelines/templates/e2e-upgrade-template.yml
- docs/manual-install.md
- docs/rotation.md
- update goreleaser config for v2
- bump version to v0.8.0
Image will be `mcr.microsoft.com/oss/v2/azure/kms` (v2) because we're building it with dalec now.
> release: bump version to v0.8.0
